name: C/C++ CI

on: [push]

jobs:
  linux_cpp:
    name: Linux C++
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Creating build dir
      run: mkdir build
    - name: Run CMake
      working-directory: ./build
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Compile
      working-directory: ./build
      run: make -j
