name: C/C++ CI

on: [push]

jobs:
  linux_cpp:
    name: Linux C++
    runs-on: ubuntu-latest
    steps:
    - name: build dir
      run: mkdir build
    - name: go to build
      run: cd build
    - name: pwd
      run: echo "$(pwd)"
    - name: cmake
      run: cmake ..
    - name: make
      run: make -j
