name: C/C++ CI

on: [push]

jobs:
  linux_cpp:
    name: Linux C++
    runs-on: ubuntu-latest
    steps:
    - name: build dir
      run: mkdir build
    - name: pwd
      run: echo "$(pwd)"
    - name: cmake
      working-directory: ./build
      run: |
        echo "$(pwd)"
        cmake ..
        make -j
